name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Debug Environment Variables
        run: echo "CYPRESS_RECORD_KEY is set"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Install Cypress Binary
        run: npx cypress install  

      #- name: Run Cypress Tests with Recording
      #  run: npx cypress run --record --key e2a46be8-a3b6-4c60-85de-d601b00ecadf
      
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          #start: npm start
          #wait-on: 'http://localhost:3000' # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          browser: chrome
          parallel: true # Runs test in parallel using settings above
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      #- name: Cypress run
      #  uses: cypress-io/github-action@v6
      #  with:
      #    #start: npm start
      #    browser: chrome
      #    record: true
      #  env:
          #CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      #    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/reports

      - name: Upload Cypress Screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
