name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Debug Environment Variables
        run: echo "CYPRESS_RECORD_KEY is set"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Install Cypress Binary
        run: npx cypress install  

      - name: Run Cypress Tests with Recording
        run: npx cypress run --record --key e2a46be8-a3b6-4c60-85de-d601b00ecadf

      #- name: Cypress run
      #  uses: cypress-io/github-action@v6
      #  with:
      #    #start: npm start
      #    browser: chrome
      #    record: true
      #  env:
          #CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
      #    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/reports

      - name: Upload Cypress Screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
