name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress Installation
        run: npx cypress info

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          #start: npm start
          browser: chrome
          record: true
        env:
          #CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      
      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/reports

      - name: Upload Cypress Screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
